import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const anime = api.anime.paradise.useQuery({ name: "One-piece" });
  // const ne = api.anime.gha.useQuery({});
  return (
    <>
      <Head>
        <title>Ghanshyam Thakkar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="bg-gradient-to-l from-stone-700 to-stone-300 py-2">
          <div className="mx-auto ">
            <div className="flex justify-between">
              <div className="mx-10 items-center font-serif text-2xl font-bold text-gray-700">
                Ghanshyam
              </div>
              <div className="mr-32 flex items-center justify-evenly rounded-lg border px-0.5 text-white">
                <div className="rounded-md border border-transparent transition delay-75 ease-in-out hover:bg-white hover:text-gray-700">
                  <a
                    href={"https://github.com/spectre10/wt-proj"}
                    target="_blank"
                    className="mx-7"
                  >
                    GitHub
                  </a>
                </div>
                <div className="mx-1 rounded-md border border-transparent transition delay-75 ease-in-out hover:bg-white hover:text-gray-700">
                  <Link href={"/about"}>
                    <div className="mx-7">About Me</div>
                  </Link>
                </div>
                <div className="rounded-md border border-transparent transition delay-75 ease-in-out hover:bg-white hover:text-gray-700">
                  <Link href={"/contact"}></Link>
                  <div className="mx-7">Contact</div>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </main>
    </>
  );
};

export default Home;
