import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import Navbar from "~/components/navbar";
import Contact from "~/components/contact";
import Footer from "~/components/footer";
import Image from "next/image";
// import { api } from "~/utils/api";

const Home: NextPage = () => {
    // const hello = api.example.hello.useQuery({ text: "from tRPC" });
    // const anime = api.anime.paradise.useQuery({ name: "One-piece" });
    // const ne = api.anime.gha.useQuery({});
    return (
        <>
            <Head>
                <title>Ghanshyam Thakkar</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <Navbar />
                <div className="flex flex-row gap-0 items-center justify-center h-screen w-full bg-[#FAE3D9] pb-20" id="about">
                    <div className="basis-1/2 flex items-center justify-center">
                        <Image src="/20230201_163523.jpg" width={500} height={300} alt="Profile pic" className="ml-60 rounded-md"/>
                    </div>
                    <div className="basis-1/2 mr-20 pr-40">
                        <p className="text-2xl font-light font-sans">Hey there, I am Ghanshyam. I am currently persuing Electronics and Communnications Engineering from L.D. College of Engineering. My interests lie in Software Development, Competitive Programming and Sports.</p>
                    </div>
                </div>
                <div className="h-[900px] bg-[#F0EDD4] border-black border-t-2 px-72" id="skills">
                    <h1 className="text-center mt-16 text-4xl font-sans mb-16">Following are the languages I am familier with:</h1>
                    <div className="text-center mb-28">
                        <ul className="list-disc list-inside text-2xl inline-block text-left">
                            <li>C++</li>
                            <li>Javascript</li>
                            <li>Golang</li>
                            <li>Python</li>
                            <li>Lua</li>
                        </ul>
                    </div>
                    <h1 className="text-center mt-20 text-4xl font-sans mb-16">Following are the technologies and skills I am most familier with:</h1>
                    <div className="grid grid-cols-3">
                        <div className="text-center">
                            <h2 className="text-2xl mb-9">Frontend:</h2>
                            <ul className="list-disc list-inside text-xl inline-block text-left">
                                <li>HTML</li>
                                <li>CSS</li>
                                <li>Javascript</li>
                                <li>ReactJS</li>
                                <li>TailwindCSS</li>
                            </ul>
                        </div>
                        <div className="text-center ">
                            <h2 className="text-2xl mb-9">Backend:</h2>
                            <ul className="list-disc list-inside text-xl inline-block text-left">
                                <li>NodeJS</li>
                                <li>ExpressJS</li>
                                <li>MongoDB</li>
                                <li>Fasthttp (Go)</li>
                                <li>tRPC</li>
                                <li>WebSockets</li>
                            </ul>
                        </div>
                        <div className="text-center">
                            <h2 className="text-2xl mb-9">Miscellaneous:</h2>
                            <ul className="list-disc list-inside text-xl inline-block text-left">
                                <li>Competitive Programming</li>
                                <li>Data Structures</li>
                                <li>Algorithms</li>
                                <li>Computer Networks</li>
                                {/* <li>tRPC</li> */}
                                {/* <li>WebSockets</li> */}
                            </ul>
                        </div>
                    </div>
                </div>
                <Contact />
                <Footer />
            </main>
        </>
    );
};

export default Home;
